## Chapter 1 _Signal Representation_

### 1.1 Introduction

1.1 Continuous-Time vs. Discrete-Time Signals

1.2 Periodic vs. Nonperiodic Signals

1.3 Periodic vs. Nonperiodic Signals

1.4 Energy and Power Signals

1.5 Transformations of the Independent Variable

1.5.1 The Shifting Operation, 10

1.5.2 The Reflection Operation, 13

1.5.3 The Time-Scaling Operation, 17

1.6 Elementary Signals

1.6.1 The Unit Step Function, 20

1.6.2 The Ramp Function, 22

1.6.3 The Sampling Function, 22

1.6.4 The Unit Impulse Function, 24

1.6.5 Derivatives of the Impulse Function, 31

1.7 Orthogonal Representations of Signals

1.8 Other Types of Signals

1.9 Summary 39

1.10 Checklist of Important Terms

1.11 Problems

* 4.5 Duration-Bandwidth Relationships 209
* 4.5.1 Definitions of Duration and Bandwidth, 209
* 4.5.2 The Uncertainty Principle, 214
* 4.6 Summary 216
* 4.7 Checklist of Important Terms 218
* 4.8 Problems 218
* 5 5 5.1 Introduction 229
* 5.2 The Bilateral Laplace Transform 230
* 5.3 The Unilateral Laplace Transform 233
* 5.4 Bilateral Transforms Using Unilateral Transforms 235
* 5.5 Properties of the Unilateral Laplace Transform 237
* 5.5.1 Linearity, 237
* 5.5.2 Time Shifting, 237
* 5.5.3 Shifting in the s Domain, 238
* 5.5.4 Time Scaling, 239
* 5.5.5 Differentiation in the Time Domain, 239
* 5.5.6 Integration in the Time Domain, 242
* 5.5.7 Differentiation in the s Domain, 244
* 5.5.8 Modulation, 244
* 5.5.9 Convolution, 245
* 5.5.10 Initial-Value Theorem, 248
* 5.5.11 Final-Value Theorem, 249
* 5.6 The Inverse Laplace Transform 252
* 5.7 Simulation Diagrams for Continuous-Time Systems 255
* 5.8 Applications of the Laplace Transform 261
* 5.8.1 Solution of Differential Equations, 261
* 5.8.2 Application of RLC Circuit Analysis, 262
* 5.8.3 Application to Control, 264
* 5.9 State Equations and the Laplace Transform 268
* 5.10 Stability in the s Domain 271
* 5.11 Summary 273
* 5.12 Checklist of Important Terms 275
* 5.13 Problems 275 

## 6 Discrete-Time Systems

### 6.1 Introduction 285

#### 6.2.1 Discrete Impulse and Step Functions, 286

_6.2.2 Exponential Sequences, 288_

_6.2.3 Scaling of Discrete-Time Signals, 291_

#### 6.3.1 System Impulse Response and the Convolution Sum, 293

_6.4_ Periodic Convolution 300_

#### 6.5Difference Equation Representation of Discrete-Time Systems 303

_6.5.1 Homogeneous Solution of the Difference Equation, 304_

_6.5.2 The Particular Solution, 306_

_6.5.3 Determination of the Impulse Response, 309_

#### 6.6Simulation Diagrams for Discrete-Time Systems 311

_6.7_ State-Variable Representation of Discrete-Time Systems 315_

_6.7.1_ Solution of State-Space Equations, 319_

_6.7.2_ Impulse Response of Systems Described by State Equations, 321_

_6.8_ Stability of Discrete-Time Systems 322_

_6.9_ Summary 323_

_6.10_ Checklist of Important Terms 324_

_6.11_ Problems 325_

## 7 Fourier Analysis of Discrete-Time Systems

### 7.1 Introduction 333

#### 7.2 Fourier-Series Representation of Discrete-Time Periodic Signals 335

_7.3_ The Discrete-Time Fourier Transform 343_

_7.4 Properties of the Discrete-Time Fourier Transform 348_

_7.4.1_ Periodicity, 348_

_7.4.2_ Linearity, 348_

_7.4.3_ Time and Frequency Shifting, 348_

_7.4.4_ Differentiation in Frequency, 348_

_7.4.5_ Convolution, 349_

_7.4.6_ Modulation, 352_

_7.4.7_ Fourier Transform of Discrete-Time Periodic Sequences, 352_

###### Contents

* 9.3.3 Alternate Inversion Formula, 407
* 9.3.4 Time Convolution, 407
* 9.3.5 Relation to the Z-Transform, 409
* 9.4 Linear Convolution Using the DFT 409
	* 9.5 Fast Fourier Transforms 411
		* 9.5.1 The Decimation-in-Time (DIT) Algorithm, 412
		* 9.5.2 The Decimation-in-Frequency (DIF) Algorithm, 416
	* 9.6 Spectral Estimation of Analog Signals Using the DFT 419
	* 9.7 Summary 425
	* 9.8 Checklist of Important Terms 426
	* 9.9 Problems 427
* 10 DESIGN OF ANALOG AND DIGITAL FILTERS
	* 10.1 Introduction 430
	* 10.2 Frequency Transformations 433
	* 10.3 Design of Analog Filters 436
		* 10.3.1 The Butterworth Filter, 436
		* 10.3.2 The Chebyshev Filter, 441
	* 10.4 Digital Filters 445
		* 10.4.1 Design of IIR Digital Filters Using Impulse Invariance, 446
		* 10.4.2 IIR Design Using the Bilinear Transformation, 450
		* 10.4.3 FIR Filter Design, 452
		* 10.4.4 Computer-Aided Design of Digital Filters, 457
	* 10.5 Summary 458
	* 10.6 Checklist of Important Terms 459
	* 10.7 Problems 459
* 10.8 Appendix A Complex Numbers
* A.1 Definition 461
* A.2 Arithmetical Operations 463
* A.2.1 Addition and Subtraction, 463
* A.2.2 Multiplication, 463
* A.2.3 Division, 464